use_frameworks!

platform :ios, '10.0'

target 'SwiftFqrs_Example' do
  pod 'SwiftFqrs', :path => '../'

  target 'SwiftFqrs_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
